language: ruby
sudo: required
services:
  - docker
script:
  - docker build -t $REPO .
after_success:
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
    docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
    docker push "$REPO";
    fi
