apiVersion: v1
kind: Service
metadata:
  name: connectorservice
  labels:
    app: connectorservice
spec:
  ports:
    - port: 8080
  selector:
    app: connectorservice
  type: ClusterIP
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: connectorservice
  labels:
    app: connectorservice
spec:
  strategy:
    type: Recreate
  replicas: 2
  template:
    metadata:
      labels:
        app: connectorservice
    spec:
      containers:
      - name: connectorservice
        image: exorath/connectorservice
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: MONGO_URI
          value: "<INSERT_URI>"
        - name: DB_NAME
          value: "connectorservice"
        - name: SERVERS_COL_NAME
          value: "servers"
        - name: ACTIONAPI_SERVICE_ADDRESS:
          value: "{ip:port}"
